### ISSUE TITLE
Ignoring errors

### ISSUE THREAD

**Issue by toqueteos** [djherbis/nio#4]
I've been reviewing the code after finding about nio thanks to the [Ok Log post][1] by Peter Bourgon.

- [ ] `bufpipe.err` is only assigned, never read from.
- [ ] Both `CloseWithError` methods (`PipeReader` & `PipeWriter`) always return `nil` (docs don't reflect that for `PipeReader`).

Are you aware of this? Is this by design?

[1]: https://peter.bourgon.org/ok-log/

**Comment by djherbis** [comment]
It is actually read from, in a few locations, albeit in can be slight tricky to notice:
 // reader quits and returns err
https://github.com/djherbis/nio/blob/master/sync.go#L92

// write quits and returns with io.ErrClosedPipe (analogous to io.Pipe)
https://github.com/djherbis/nio/blob/master/sync.go#L121 

It's non-obvious that this is the error being read here because I'm calling a field on bufpipe which is exposed via embedding.

I mainly tried to clone the behavior of io.Pipe (while adding the buffering).
https://github.com/golang/go/blob/d296c3235d47ab1a0e5077dfcfbc3e14854e38c5/src/io/pipe.go#L143
https://github.com/golang/go/blob/d296c3235d47ab1a0e5077dfcfbc3e14854e38c5/src/io/pipe.go#L173

io.Pipe's CloseWithError methods also always return null so I matched that.

That being said there a couple behavior differences (and one could argue I should change them).

The write method can only return CloseWithError right now (while io.Pipe can return the CloseWithError from the reader).

I did find something which may be a problem, if you call write (and it's too big for the buffer), I only check if you've closed the pipe at the start and I expect it to be able to write to the buffer from there on, I'll fix that so that it will cancel the current write rather than block.

**Comment by djherbis** [comment]
The err handling should work almost exactly the same as io.Pipe now (it was already similar, but the CloseWithError cases are better now) and once you call Close (or CloseWithError) it should guarantee that blocking Read/Writes will unblock.

None of these changes should change "normal" behavior though. If you were only calling close after you're done writing, then you shouldn't see changes.

**Comment by toqueteos** [comment]
I was tripping very hard with `.CloseWithError` always returning `nil` in the PipeReader case but yeah.. it's all about `rerr` and `werr` on `.Read`. My bad.

Still, `PipeReader.CloseWithError` is lacking a `CloseWithError always returns nil.` in its docs, like the PipeWriter version does. Besides that... If both methods do always return nil then what's the point of returning anything at all?

Thank you very much for the explanation and hey if that helped you to get so other thing solved everyone wins! Thank you very much for this library! 👍

**Comment by djherbis** [comment]
I'll update the docs after work today, I forgot to add that it always returns nil when I was updating the other stuff. I do question why it even has a err return when it's always nil, but I wanted API comparability with io.Pipe (they don't mention it in their docs either...!?).

Always happy to help, and I appreciate you doing a review, it did force me to review stuff and fix that issue!

Hope you enjoy the lib, have a great week!
